# Generated by Django 4.0.3 on 2022-04-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
