# Generated by Django 4.0.3 on 2022-04-02 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_carspecification_car_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carspecification',
            name='car_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.carplan'),
        ),
    ]
